SOURCES=closures.c debug.c java_raw_api.c prep_cif.c raw_api.c types.c \
	x86/ffi.c x86/ffi64.c x86/sysv.S x86/win32.S

CUSTOM_DEFINES=
CUSTOM_INCLUDES=./src ./linux/i686-pc-linux-gnu
CUSTOM_CCFLAGS=
