NAME=libxslt
TYPE=archive

include ../../rules/environment.linux.makefile

SOURCES=attributes.c attrvt.c documents.c extensions.c \
	functions.c imports.c keys.c namespaces.c \
	numbers.c pattern.c preproc.c templates.c transform.c \
	variables.c xslt.c xsltlocale.c xsltutils.c

CUSTOM_DEFINES=

CUSTOM_INCLUDES=./include/libxslt ./include ./src

CUSTOM_CCFLAGS=

include ../../rules/archive.linux.makefile
