NAME=libcef
TYPE=archive

include ../../rules/environment.linux.makefile

SOURCES=\
	cefstubs.cpp

SOURCE_DIR=libcef_dll

CUSTOM_DEFINES=

CUSTOM_INCLUDES=

CUSTOM_CCFLAGS=

$(SOURCE_DIR)/cefstubs.cpp: libcef.stubs ../../util/weak_stub_maker.pl
	mkdir -p $(SOURCE_DIR)
#	../../prebuilt/bin/Revolution.lnx "../../tools/weak_stub_maker.lc" <./ssl.stubs >$(SOURCE_DIR)/sslstubs.cpp
	../../util/weak_stub_maker.pl <./libcef.stubs >$(SOURCE_DIR)/cefstubs.cpp

include ../../rules/archive.linux.makefile
